{
 "title": "recent-messages",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": "label_values(instance)" },
   { "name": "job", "query": "label_values(job)" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Up/Down",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{instance=~\"$instance\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "format": "dthms",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=~\"$instance\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Wanted Channels",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "twitch_irc_channels{instance=~\"$instance\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Joined Channels",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "twitch_irc_channels{instance=~\"$instance\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Joined Ratio",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "twitch_irc_channels{instance=~\"$instance\",job=~\"$job\",type=\"joined\"} / ignoring(type) twitch_irc_channels{instance=~\"$instance\",job=~\"$job\",type=\"wanted\"} * 100"
    }
   ]
  },
  {
   "title": "Incoming messages",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(twitch_irc_messages_received{instance=~\"$instance\",job=~\"$job\",command=\"PRIVMSG\"}[30s]))"
    }
   ]
  },
  {
   "title": "Connections (total)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(twitch_irc_connections{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Connections connected",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 17, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "twitch_irc_connections{instance=~\"$instance\",job=~\"$job\",type=\"ready\"} / ignoring(instance, job, type) sum(twitch_irc_connections{instance=~\"$instance\",job=~\"$job\"}) * 100"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 } },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Messages (30s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(twitch_irc_messages_received{instance=~\"$instance\",job=~\"$job\"}[30s])",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "sum(rate(twitch_irc_messages_received{instance=~\"$instance\",job=~\"$job\"}[30s]))",
     "legendFormat": "all commands"
    }
   ]
  },
  {
   "title": "Connected channels",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "twitch_irc_channels{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Messages (10m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(twitch_irc_messages_received{instance=~\"$instance\",job=~\"$job\"}[10m])",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "sum(rate(twitch_irc_messages_received{instance=~\"$instance\",job=~\"$job\"}[10m]))",
     "legendFormat": "all commands"
    }
   ]
  },
  {
   "title": "Channel count 10 minute increase/decrease",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(twitch_irc_channels{instance=~\"$instance\",job=~\"$job\",type=\"wanted\"}[10m])",
     "legendFormat": "Channel increase/decrease"
    }
   ]
  },
  {
   "title": "Messages (2d)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(twitch_irc_messages_received{instance=~\"$instance\",job=~\"$job\"}[2d])",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Reconnects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "increase(twitch_irc_reconnects{instance=~\"$instance\",job=~\"$job\"}[$__interval])",
     "legendFormat": "Reconnects"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "twitch_irc_connections{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Performance statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Process CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total{instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "User"
    },
    {
     "expr": "rate(process_cpu_system_seconds_total{instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "System"
    },
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Heap memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_heap_bytes{instance=~\"$instance\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "node.js event loop lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(nodejs_eventloop_lag_seconds{instance=~\"$instance\",job=~\"$job\"}[10m])"
    }
   ]
  },
  { "title": "Request statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "average response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{instance=~\"$instance\",job=~\"$job\"}[30m])) / sum(rate(http_request_duration_milliseconds_count{instance=~\"$instance\",job=~\"$job\"}[30m]))",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "requests per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{instance=~\"$instance\",job=~\"$job\"}[1m]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{instance=~\"$instance\",job=~\"$job\"}[24h]))",
     "legendFormat": "total, 24h avg"
    }
   ]
  },
  {
   "title": "percentile response times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{instance=~\"$instance\",job=~\"$job\"}[1m])) by (le))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket{instance=~\"$instance\",job=~\"$job\"}[1m])) by (le))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{instance=~\"$instance\",job=~\"$job\"}[1m])) by (le))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Requests per second, 4xx/5xx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{instance=~\"$instance\",job=~\"$job\",status_code=~\"^[45].*\"}[1m])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "requests per second (24h avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{instance=~\"$instance\",job=~\"$job\"}[24h]))",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "Garbage Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(nodejs_gc_pause_seconds_total{instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{gctype}}"
    }
   ]
  },
  {
   "title": "GC reclaimed data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(nodejs_gc_reclaimed_bytes_total{instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{gctype}}"
    }
   ]
  },
  {
   "title": "GC run rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(nodejs_gc_runs_total{instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{gctype}}"
    }
   ]
  }
 ]
}